### ISSUE TITLE
Create Navbar components

### ISSUE THREAD

**Issue by TrustedMercury** [teamcodebyte/haven-frontend#10]
## Description
Provide a clear and concise description of the feature you're suggesting
```
Create 2 navbar components in /src/components

One navbar component is HomeNavbar which follows this design - https://zpl.io/aNNB7zZ
The other navbar component is Navbar which follows this design - https://zpl.io/2jNkoM6
```

**Comment by TrustedMercury** [comment]
Also, this needs to merge to branch 8, so create a branch/fork on top of that

**Comment by DiscordAnaxes** [comment]
Status:

- Footer 98%

- HomeNavbar 0%

- Navbar 0%

**Comment by GreatGuy96** [comment]
Please close this issue:
Though the navbar for other purposes have not been done, the navbars mentioned in this issue, specifically the ones for when one is signed out, are done.
