### ISSUE TITLE
Minor Components in src/components/utility.js

### ISSUE THREAD

**Issue by TrustedMercury** [teamcodebyte/haven-frontend#15]
## Description

Create a bunch of minor components that will be re-used throughout the webpage, all of them should be able to be imported from the utility.js file

Leave this issue and PR open, we'll have to constantly add new components to utility.js

Components -
- logo
- button

## Credit

* @GreatGuy96

**Comment by GreatGuy96** [comment]
Could you update this issue to show that the logo component is now done and that the button component has been removed?
