### ISSUE TITLE
Create Footer component in src/components/Footer.js

### ISSUE THREAD

**Issue by TrustedMercury** [teamcodebyte/haven-frontend#16]
## Description

Create a Footer component in src/components/Footer.js

Follow designs here (you need access to the Zeplin, DM me on Discord) - https://zpl.io/bzQyB6X 

## Credit

* @DiscordAnaxes

**Comment by DiscordAnaxes** [comment]
Currently doing.

**Comment by GreatGuy96** [comment]
Please close this issue, there already is a footer, yet no sign in this issue that it was already made
